steps:
 # Build the application
 - name: 'golang:1.18'
   entrypoint: go
   env: ['CGO_ENABLED=0']
   args: ['build', '-o', 'cmd/backend/.bin', './cmd/backend']
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE', 'cmd/backend']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - '$_SERVICE'
   - '--image'
   - 'gcr.io/$PROJECT_ID/$_SERVICE'
   - '--region'
   - '$_REGION'
   - '--platform'
   - 'managed'
substitutions:
  # User-defined substitutions must begin with underscore (https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#using_user-defined_substitutions)
   _SERVICE: doc-publisher-backend
   _REGION: us-central1